package com.cognizant.dev.portal.models;

public enum RoomType {
	
	SINGLE_ECONOMY, SINGLE_BASIC, SINGLE_STANDARD, SINGLE_DELUX, 
	DOUBLE_ECONOMY, DOUBLE_BASIC, DOUBLE_STANDARD, DOUBLE_DELUX,
	FAMILY_ECONOMY, FAMILY_BASIC, FAMILY_STANDARD, FAMILY_DELUX,
	PRESIDENTIAL

}
